version: '3'
services:

  webapp:
    build: .
    image: webapp
    depends_on:
        - mysql
        - redis
        - memcached
    environment:
      - PROJECT_ENV=PRODUCTION
      - MEMCACHED_HOST=memcached
      - REDIS_HOST=redis
      - HOST=myshop.ru
      - DB_NAME=django_shop
      - DB_PASSWORD=123456
      - DB_USER=Admin
      - DB_HOST=mysql
    volumes:
      - ./staticfiles:/project/staticfiles
    entrypoint: ["./boot.sh"]

  redis:
    restart: always
    image: redis

  memcached:
    restart: always
    image: memcached

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx_prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/srv/static
    depends_on:
      - webapp

  celery:
#    build: .
    image: webapp
    environment:
    - REDIS_HOST=redis
    depends_on:
      - redis
      - webapp
    command: /bin/bash -c "cd django_shop && exec celery -A shop worker -l info"

  mysql:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./etc/mysql_prod.cnf:/etc/mysql/conf.d/mysql_prod.cnf
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=django_shop
      - MYSQL_USER=Admin
      - MYSQL_PASSWORD=123456


